name: Deploy to Azure Container App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build ./container-azure-deployment-api/container-azure-deployment-api.csproj --configuration Release

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  
        tenant-id: ${{ secrets.AZURE_TENANT_ID }} 
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to ACR via Azure CLI
      run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

    - name: Build and push container image to ACR
      uses: docker/build-push-action@v6
      with:
        context: container-azure-deployment-api
        push: true
        tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.CONTAINER_APP_NAME }}:${{ github.sha }}
        file: container-azure-deployment-api/Dockerfile

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.CONTAINER_APP_NAME }}:${{ github.sha }}
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
        containerAppName: ${{ secrets.CONTAINER_APP_NAME }}
        environmentVariables: |
          ASPNETCORE_ENVIRONMENT=Development
